version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - automerge-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      POSTGRES_DB: automerge_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - automerge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d automerge_sync"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  postgres-data:

networks:
  automerge-network:
    driver: bridge
