services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - automerge-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      POSTGRES_DB: automerge_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - automerge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d automerge_sync"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

  neo4j:
    image: neo4j:5.15-community
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-conf:/conf
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    networks:
      - automerge-network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j123", "RETURN 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres-data:
  neo4j-data:
  neo4j-logs:
  neo4j-conf:
  neo4j-import:
  neo4j-plugins:

networks:
  automerge-network:
    driver: bridge
